import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const isProd = process.argv[2] === "production";

// Copy static assets to dist/
function copyStaticAssets() {
  if (!fs.existsSync("dist")) {
    fs.mkdirSync("dist", { recursive: true });
  }
  if (fs.existsSync("manifest.json")) {
    fs.copyFileSync("manifest.json", "dist/manifest.json");
  }
  if (fs.existsSync("styles.css")) {
    fs.copyFileSync("styles.css", "dist/styles.css");
  }
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.js"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr"
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: isProd ? false : "inline",
  treeShaking: true,
  outfile: "dist/main.js",
  minify: isProd,
  plugins: [
    {
      name: "copy-assets-plugin",
      setup(build) {
        build.onEnd((result) => {
          if (result.errors.length === 0) {
            copyStaticAssets();
            // Also maintain root main.js for direct Obsidian development
            if (fs.existsSync("dist/main.js")) {
              fs.copyFileSync("dist/main.js", "main.js");
            }
            console.log("Build completed successfully -> dist/ and root updated.");
          }
        });
      }
    }
  ]
});

if (isProd) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
  console.log("Watching for changes in src/...");
}
