export const DEFAULT_SETTINGS = {
  tabsKeyword: "tabs",
  split: "tab: ",
  defaultTabNavItem: "New tab",
  defaultTabNavItemVertical: "New vertical tab",
  verticalTabsColumns: "1",
  defaultTabContent: "New tab content",
  actionButtonType: "action-add",
  ignoreNotice: false,
  autorefreshMarkdownView: true,
  dragAndDrop: false,
  doubleClickToEdit: false,
  showToolbar: true,
  tabSize: 4,
  editorAutoSaveInterval: 5000,
  defaultTabsBorder: "border-hover",
  defaultTabsBorderColor: "#e0e0e0",
  hideTabsEditBlockButton: true,
  defaultTitleLineClamp: "one",
  defaultTitlePosition: "top",
  defaultTitleLimited: false,
  defaultTabsContentsPadding: "1em 2em",
  defaultTabsContentsMaxHeight: "none",
  nestedTabsHighlight: true,
  nestedTabsNoBorders: true,
  nestedTabsDelimiterTextStart: "nesting start",
  nestedTabsDelimiterTextEnd: "nesting end",
  nestedTabsDelimiterColorLight: "#808080",
  nestedTabsDelimiterColorDark: "#aaaaaa",
  nestedTabsItemColorLight: "#4CAF50",
  nestedTabsItemColorDark: "#81C784",
  nestedTabsDifferentDarkColor: false,
  nestedTabsItemUnderlineThickness: 2,
  nestedTabsItemUnderlineOffset: 2,
  nestedTabsItemUnderlineStyle: "solid",
  nestedTabsItemUnderlineOpacity: 100,
  nestedTabsColorLevel0: "#4a90e2",
  nestedTabsColorLevel1: "#50e3c2",
  nestedTabsColorLevel2: "#f5a623",
  nestedTabsColorLevel3: "#b8e986",
  nestedTabsColorLevel4: "#bd10e0",
  nestedTabsColorLevel5Plus: "#888888",
  language: "es",
  tabsSeparatorFontSize: 14,
  tabsSeparatorBgOpacity: 30,
  deleteButtonSpacing: 12,
  deleteIconStyle: "trash",
  verticalTabsLeftSpacing: 4,
  verticalTabsRightSpacing: 8,
  horizontalTabTitleFontSize: 13,
  verticalTabTitleFontSize: 13,
  verticalTitleBehavior: "hover-scroll",
  verticalTitleAlignment: "left",
  tabContentAlignment: "left",
  tabContentHyphenation: "none"
};
