export const DEFAULT_SETTINGS = {
  split: "tema:",
  defaultTabNavItem: "New tab",
  defaultTabNavItemVertical: "New vertical tab",
  defaultTabContent: "New tab content",
  actionButton: "action-add",
  ignoreNotice: false,
  autorefreshMarkdownView: true,
  dragAndDrop: true,
  closeOthersOnActive: false,
  tabsKeyword: "tabs",
  tabsKeywordEnable: true,
  tabsBorder: true,
  tabsAlign: "center",
  tabsCloseButton: true,
  nestedTabsNoBorders: false,
  nestedTabsDelimiterColorStart: "#6b7280",
  nestedTabsDelimiterColorEnd: "#6b7280",
  nestedTabsDelimiterTextColorStart: "#6b7280",
  nestedTabsDelimiterTextColorEnd: "#6b7280",
  nestedTabsDelimiterTextStart: "nesting start",
  nestedTabsDelimiterTextEnd: "nesting end",
  nestedTabsEmptyTitleText: "ingresa un título para esta pestaña",
  nestedTabLevelsColorsDark: ["#e06c75", "#98c379", "#e5c07b", "#61afef", "#c678dd", "#56b6c2"],
  nestedTabLevelsColorsLight: ["#e45649", "#50a14f", "#c18401", "#4078f2", "#a626a4", "#0184bc"],
  nestedTabLevelsDelimiterColorsDark: ["#e06c75", "#98c379", "#e5c07b", "#61afef", "#c678dd", "#56b6c2"],
  nestedTabLevelsDelimiterColorsLight: ["#e45649", "#50a14f", "#c18401", "#4078f2", "#a626a4", "#0184bc"],
  verticalTitleAlignment: "left",
  titleRowLayout: "single_line",
  limitWidth: true,
  containerBorder: "always",
  borderColor: "",
  contentPadding: "",
  maxHeight: "",
  deleteSpacing: "8",
  deleteIcon: "trash",
  language: "es"
};
